import mongoose from "mongoose";
import { connectDB } from "./db";
import { Suggestion } from "@/models/Suggestions";

/* ------------------------------------------------------------------
   MANUALLY CURATED FINANCE SUGGESTIONS (KEEP THESE)
------------------------------------------------------------------- */

const financeSuggestions = [
  // --- BASICS & SAVINGS ---
  "How to invest in Mutual Funds?",
  "What is a SIP (Systematic Investment Plan)?",
  "How to create a monthly budget?",
  "Emergency fund planning strategies",
  "Difference between Savings Account and Liquid Fund",
  "How does inflation affect my savings?",
  "What is the 50-30-20 rule of budgeting?",
  "How to improve my CIBIL credit score?",
  "Benefits of compound interest explained",

  // --- STOCK MARKET ---
  "Best stocks for long term investment",
  "What is the difference between Nifty and Sensex?",
  "How to analyze a stock balance sheet?",
  "Explain P/E Ratio (Price to Earnings)",
  "Difference between Large Cap, Mid Cap, and Small Cap",
  "What is an IPO (Initial Public Offering)?",
  "How to read a candlestick chart?",
  "What is a Demat account and how to open one?",
  "Difference between Intraday and Delivery trading",
  "How to pick dividend paying stocks?",
  "What are Blue Chip stocks?",

  // --- TAX SAVING ---
  "How to save tax in India (Section 80C)?",
  "Best ELSS funds for tax saving",
  "What is the difference between STCG and LTCG tax?",
  "Tax benefits of Home Loans (Section 24)",
  "How to file ITR (Income Tax Return)?",
  "Is NPS (National Pension System) good for tax saving?",
  "Taxation on Cryptocurrency in India",

  // --- ASSET COMPARISONS ---
  "Gold vs Real Estate investment",
  "Sovereign Gold Bonds (SGB) vs Physical Gold",
  "Fixed Deposit (FD) vs Debt Mutual Funds",
  "Stocks vs Real Estate: Which gives better returns?",
  "Rent vs Buy: Should I buy a house?",

  // --- RETIREMENT ---
  "How to plan for early retirement (FIRE)?",
  "What is PPF (Public Provident Fund)?",
  "EPF vs PPF: Which is better?",
  "How much corpus do I need for retirement?",
  "Best retirement pension plans in India",

  // --- ADVANCED ---
  "High risk vs Low risk investment options",
  "Cryptocurrency risks and regulations",
  "What are ETFs (Exchange Traded Funds)?",
  "What are REITs (Real Estate Investment Trusts)?",
  "Hedging strategies against market crash",
  "What is Future and Options (F&O) trading?",
  "Understanding Beta and Alpha in stocks",

  // --- SCENARIOS ---
  "How to invest 10,000 rupees monthly?",
  "Best investment options for students",
  "Where to invest a lump sum amount?",
  "How to diversify my investment portfolio?",
  "Safe investments for senior citizens"
];

/* ------------------------------------------------------------------
   AUTO-GENERATION LOGIC (1000+ ENTRIES)
------------------------------------------------------------------- */

const investmentAmounts = [
  "₹5,000",
  "₹10,000",
  "₹25,000",
  "₹50,000",
  "₹1 Lakh",
  "₹5 Lakhs",
  "₹10 Lakhs"
];

const userProfiles = [
  "students",
  "beginners",
  "working professionals",
  "freelancers",
  "senior citizens",
  "high income earners",
  "first-time investors"
];

const assets = [
  "stocks",
  "mutual funds",
  "ETFs",
  "index funds",
  "gold",
  "bonds",
  "cryptocurrency",
  "real estate",
  "PPF",
  "NPS"
];

const actions = [
  "How to invest in",
  "Best way to invest in",
  "Is it safe to invest in",
  "Tax implications of",
  "Long term returns from",
  "Risks associated with",
  "Beginner guide to",
  "Advanced strategies for",
  "Should I invest in"
];

const timeHorizons = [
  "for long term",
  "for short term",
  "for retirement",
  "for passive income",
  "during market volatility",
  "in high inflation",
  "during economic slowdown"
];

const generateFinanceSuggestions = (limit = 1000): string[] => {
  const generated = new Set<string>();

  while (generated.size < limit) {
    const suggestion = `${actions[random(actions)]} ${
      assets[random(assets)]
    } ${timeHorizons[random(timeHorizons)]} for ${
      userProfiles[random(userProfiles)]
    } with ${investmentAmounts[random(investmentAmounts)]}`;

    generated.add(suggestion.trim());
  }

  return Array.from(generated);
};

const random = (arr: string[]) =>
  Math.floor(Math.random() * arr.length);

/* ------------------------------------------------------------------
   SEED SCRIPT
------------------------------------------------------------------- */

const seedData = async () => {
  await connectDB();

  try {
    console.log("🌱 Seeding finance suggestions...");

    // Optional: clear old data
    await Suggestion.deleteMany({});
    console.log("🧹 Old suggestions cleared");

    const autoGenerated = generateFinanceSuggestions(1000);

    const ALL_SUGGESTIONS = [
      ...financeSuggestions,
      ...autoGenerated
    ];

    const docs = ALL_SUGGESTIONS.map(text => ({
      text,
      category: "Finance",
      popularity: Math.floor(Math.random() * 100) + 1
    }));

    await Suggestion.insertMany(docs);

    console.log(`✅ Successfully seeded ${docs.length} suggestions`);

  } catch (error) {
    console.error("❌ Error seeding data:", error);
  } finally {
    await mongoose.disconnect();
    console.log("🔌 MongoDB disconnected");
  }
};

seedData();
